source 'https://github.com/Tovema-iOS/Specs.git'
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

platform :ios, '8.0'

target 'TMCollectionViewTemplate_Example' do
  pod 'TMCollectionViewTemplate', :path => '../'

  target 'TMCollectionViewTemplate_Tests' do
    inherit! :search_paths

    
  end
end
